swagger: '2.0'
info:
  title: API de Usuários
  description: API para gerenciamento de usuários
  version: 1.0.0
host: localhost:5000
basePath: /
schemes:
  - http
  - https
paths:
  /usuarios:
    get:
      description: Retorna todos os usuários
      responses:
        '200':
          description: OK
    post:
      description: Cria um novo usuário
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              cpf:
                type: integer
                example: 12345678901
              nome:
                type: string
                example: João da Silva
              data_nascimento:
                type: string
                format: date
                example: 2000-01-01
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
  /usuarios/{cpf}:
    get:
      description: Retorna um usuário pelo CPF
      parameters:
        - name: cpf
          in: path
          required: true
          type: integer
          example: 12345678901
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
